version: "3.5"
services:
  otel-collector:
    container_name: otel-collector-contrib
    image: otel/opentelemetry-collector-contrib:0.64.0
    command: ["--config=/etc/otelcol-config.yaml"]
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    volumes:
      - ./otel-config.yaml:/etc/otelcol-config.yaml
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
