extensions:
  basicauth/prw/1:
    client_auth:
      # Replace these variables by their actual values
      username: d425751e-****
      password: c4b75737d****
  basicauth/prw/2:
    client_auth:
      # Replace these variables by their actual values
      username: ca1bfe79****
      password: f4f270e****

receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector-01'
        scrape_interval: 60s
        static_configs:
        - targets: ['otel-collector:8888', 'app:8000']

processors:
  filter/1:
    metrics:
      include:
        match_type: expr
        expressions:
        - MetricName == "levitate_request_counts_total" && HasLabel("path") == true
  filter/2:
    metrics:
      include:
        match_type: expr
        expressions:
        - MetricName == "levitate_request_counts_total" && HasLabel("path") == false

exporters:
  prometheusremotewrite/1:
    auth:
      authenticator: basicauth/prw/1
    endpoint: "https://alpha-tsdb.last9.io/v1/metrics/bb79e5ff****/sender/last9/write"
  prometheusremotewrite/2:
    auth:
      authenticator: basicauth/prw/2
    endpoint: "https://alpha-tsdb.last9.io/v1/metrics/bb79e5ff****/sender/last9/write"

service:
  extensions: [basicauth/prw/1, basicauth/prw/2]
  pipelines:
    metrics/1:
      receivers: [prometheus]
      processors: [filter/1]
      exporters: [prometheusremotewrite/1]
    metrics/2:
      receivers: [prometheus]
      processors: [filter/2]
      exporters: [prometheusremotewrite/2]
