# metric source <--- receiver (prometheus scrape config) ---> processor (none) ---> exporter (remotewrite) + extension (basicauth) --> levitate
extensions:
  basicauth/prw/1:
    client_auth:
      # Replace these variables by their actual values
      username: username1
      password: password1
  basicauth/prw/2:
    client_auth:
      # Replace these variables by their actual values
      username: username2
      password: password2

receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector-01'
        scrape_interval: 60s
        static_configs:
        - targets: ['otel-collector:8888']

processors:
  filter/1:
    metrics:
      exclude:
        match_type: expr
        expressions:
        - MetricName == "my.metric" && Label("my_label") == "abc123"
  filter/2:
    metrics:
      exclude:
        match_type: expr
        expressions:
        - MetricName == "my.other.metric"
exporters:
  prometheusremotewrite/1:
    auth:
      authenticator: basicauth/prw
    endpoint: "<Cluster 1>" # Replace with backend 1 URL
  prometheusremotewrite/2:
    auth:
      authenticator: basicauth/prw
    endpoint: "<Cluster 2>" # Replace with backend 2 URL

service:
  extensions: [basicauth/prw/1, basicauth/prw/2]
  pipelines:
    metrics/1:
      receivers: [prometheus]
      processors: [filter/1]
      exporters: [prometheusremotewrite/1]
    metrics/2:
      receivers: [prometheus]
      processors: [filter/2]
      exporters: [prometheusremotewrite/2]
